//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace MSNPSharp.MSNStorageService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MSNStorageServiceBinding", Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class MSNStorageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private StorageApplicationHeader storageApplicationHeaderValueField;
        
        private StorageUserHeader storageUserHeaderValueField;
        
        private AffinityCacheHeader affinityCacheHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MSNStorageService() {
            this.Url = global::MSNPSharp.Properties.Settings.Default.MSNPSharp_MSNStorageService_MSNStorageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public StorageApplicationHeader StorageApplicationHeaderValue {
            get {
                return this.storageApplicationHeaderValueField;
            }
            set {
                this.storageApplicationHeaderValueField = value;
            }
        }
        
        public StorageUserHeader StorageUserHeaderValue {
            get {
                return this.storageUserHeaderValueField;
            }
            set {
                this.storageUserHeaderValueField = value;
            }
        }
        
        public AffinityCacheHeader AffinityCacheHeaderValue {
            get {
                return this.affinityCacheHeaderValueField;
            }
            set {
                this.affinityCacheHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProfileCompletedEventHandler GetProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/w10/GetProfile", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProfileResponse", Namespace="http://www.msn.com/webservices/storage/w10")]
        public GetProfileResponse GetProfile([System.Xml.Serialization.XmlElementAttribute("GetProfile", Namespace="http://www.msn.com/webservices/storage/w10")] GetProfileRequestType GetProfile1) {
            object[] results = this.Invoke("GetProfile", new object[] {
                        GetProfile1});
            return ((GetProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileAsync(GetProfileRequestType GetProfile1) {
            this.GetProfileAsync(GetProfile1, null);
        }
        
        /// <remarks/>
        public void GetProfileAsync(GetProfileRequestType GetProfile1, object userState) {
            if ((this.GetProfileOperationCompleted == null)) {
                this.GetProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileOperationCompleted);
            }
            this.InvokeAsync("GetProfile", new object[] {
                        GetProfile1}, this.GetProfileOperationCompleted, userState);
        }
        
        private void OnGetProfileOperationCompleted(object arg) {
            if ((this.GetProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileCompleted(this, new GetProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/storage/w10", IsNullable=false)]
    public partial class StorageUserHeader : System.Web.Services.Protocols.SoapHeader {
        
        private int puidField;
        
        private int cidField;
        
        private string ticketTokenField;
        
        private bool isAdminField;
        
        public StorageUserHeader() {
            this.puidField = 0;
            this.cidField = 0;
            this.isAdminField = false;
        }
        
        /// <remarks/>
        public int Puid {
            get {
                return this.puidField;
            }
            set {
                this.puidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Cid {
            get {
                return this.cidField;
            }
            set {
                this.cidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string TicketToken {
            get {
                return this.ticketTokenField;
            }
            set {
                this.ticketTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class GetProfileResultType {
        
        private string resourceIDField;
        
        private System.DateTime dateModifiedField;
        
        private GetProfileResultTypeExpressionProfile expressionProfileField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public GetProfileResultTypeExpressionProfile ExpressionProfile {
            get {
                return this.expressionProfileField;
            }
            set {
                this.expressionProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class GetProfileResultTypeExpressionProfile {
        
        private string resourceIDField;
        
        private System.DateTime dateModifiedField;
        
        private int flagsField;
        
        private object photoField;
        
        private string personalStatusField;
        
        private System.DateTime personalStatusLastModifiedField;
        
        private string displayNameField;
        
        private System.DateTime displayNameLastModifiedField;
        
        private string staticUserTilePublicURLField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public int Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
        
        /// <remarks/>
        public object Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalStatus {
            get {
                return this.personalStatusField;
            }
            set {
                this.personalStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PersonalStatusLastModified {
            get {
                return this.personalStatusLastModifiedField;
            }
            set {
                this.personalStatusLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DisplayNameLastModified {
            get {
                return this.displayNameLastModifiedField;
            }
            set {
                this.displayNameLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string StaticUserTilePublicURL {
            get {
                return this.staticUserTilePublicURLField;
            }
            set {
                this.staticUserTilePublicURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class profileAttributes {
        
        private bool resourceIDField;
        
        private bool dateModifiedField;
        
        private profileAttributesExpressionProfileAttributes expressionProfileAttributesField;
        
        public profileAttributes() {
            this.resourceIDField = true;
            this.dateModifiedField = true;
        }
        
        /// <remarks/>
        public bool ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public bool DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public profileAttributesExpressionProfileAttributes ExpressionProfileAttributes {
            get {
                return this.expressionProfileAttributesField;
            }
            set {
                this.expressionProfileAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class profileAttributesExpressionProfileAttributes {
        
        private bool resourceIDField;
        
        private bool dateModifiedField;
        
        private bool displayNameField;
        
        private bool displayNameLastModifiedField;
        
        private bool personalStatusField;
        
        private bool personalStatusLastModifiedField;
        
        private bool staticUserTilePublicURLField;
        
        private bool photoField;
        
        private bool flagField;
        
        public profileAttributesExpressionProfileAttributes() {
            this.resourceIDField = true;
            this.dateModifiedField = true;
            this.displayNameField = true;
            this.displayNameLastModifiedField = true;
            this.personalStatusField = true;
            this.personalStatusLastModifiedField = true;
            this.staticUserTilePublicURLField = true;
            this.photoField = true;
            this.flagField = true;
        }
        
        /// <remarks/>
        public bool ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public bool DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public bool DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public bool DisplayNameLastModified {
            get {
                return this.displayNameLastModifiedField;
            }
            set {
                this.displayNameLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        public bool PersonalStatus {
            get {
                return this.personalStatusField;
            }
            set {
                this.personalStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool PersonalStatusLastModified {
            get {
                return this.personalStatusLastModifiedField;
            }
            set {
                this.personalStatusLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        public bool StaticUserTilePublicURL {
            get {
                return this.staticUserTilePublicURLField;
            }
            set {
                this.staticUserTilePublicURLField = value;
            }
        }
        
        /// <remarks/>
        public bool Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        public bool Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class profileHandle {
        
        private profileHandleAlias aliasField;
        
        private string relationshipNameField;
        
        public profileHandle() {
            this.relationshipNameField = "MyProfile";
        }
        
        /// <remarks/>
        public profileHandleAlias Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string RelationshipName {
            get {
                return this.relationshipNameField;
            }
            set {
                this.relationshipNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class profileHandleAlias {
        
        private string nameField;
        
        private string nameSpaceField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string NameSpace {
            get {
                return this.nameSpaceField;
            }
            set {
                this.nameSpaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class GetProfileRequestType {
        
        private profileHandle profileHandleField;
        
        private profileAttributes profileAttributesField;
        
        /// <remarks/>
        public profileHandle profileHandle {
            get {
                return this.profileHandleField;
            }
            set {
                this.profileHandleField = value;
            }
        }
        
        /// <remarks/>
        public profileAttributes profileAttributes {
            get {
                return this.profileAttributesField;
            }
            set {
                this.profileAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/storage/w10", IsNullable=false)]
    public partial class AffinityCacheHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string cacheKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string CacheKey {
            get {
                return this.cacheKeyField;
            }
            set {
                this.cacheKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/storage/w10", IsNullable=false)]
    public partial class StorageApplicationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string applicationIDField;
        
        private string scenarioField;
        
        public StorageApplicationHeader() {
            this.applicationIDField = "Messenger Client 8.5";
            this.scenarioField = "Initial";
        }
        
        /// <remarks/>
        public string ApplicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        public string Scenario {
            get {
                return this.scenarioField;
            }
            set {
                this.scenarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/w10")]
    public partial class GetProfileResponse {
        
        private GetProfileResultType getProfileResultField;
        
        /// <remarks/>
        public GetProfileResultType GetProfileResult {
            get {
                return this.getProfileResultField;
            }
            set {
                this.getProfileResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetProfileCompletedEventHandler(object sender, GetProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProfileResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591