//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.1433 版自动生成。
// 
#pragma warning disable 1591

namespace MSNPSharp.MSNWS.MSNSpaceService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SpaceServiceBinding", Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class SpaceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthTokenHeader authTokenHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetXmlFeedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SpaceService() {
            this.Url = global::MSNPSharp.Properties.Settings.Default.MSNPSharp_MSNWS_MSNSpaceService_SpaceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthTokenHeader AuthTokenHeaderValue {
            get {
                return this.authTokenHeaderValueField;
            }
            set {
                this.authTokenHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetXmlFeedCompletedEventHandler GetXmlFeedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/spaces/v1/GetXmlFeed", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetXmlFeedResponse", Namespace="http://www.msn.com/webservices/spaces/v1/")]
        public GetXmlFeedResponseType GetXmlFeed([System.Xml.Serialization.XmlElementAttribute("GetXmlFeed", Namespace="http://www.msn.com/webservices/spaces/v1/")] GetXmlFeedRequestType GetXmlFeed1) {
            object[] results = this.Invoke("GetXmlFeed", new object[] {
                        GetXmlFeed1});
            return ((GetXmlFeedResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetXmlFeedAsync(GetXmlFeedRequestType GetXmlFeed1) {
            this.GetXmlFeedAsync(GetXmlFeed1, null);
        }
        
        /// <remarks/>
        public void GetXmlFeedAsync(GetXmlFeedRequestType GetXmlFeed1, object userState) {
            if ((this.GetXmlFeedOperationCompleted == null)) {
                this.GetXmlFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXmlFeedOperationCompleted);
            }
            this.InvokeAsync("GetXmlFeed", new object[] {
                        GetXmlFeed1}, this.GetXmlFeedOperationCompleted, userState);
        }
        
        private void OnGetXmlFeedOperationCompleted(object arg) {
            if ((this.GetXmlFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXmlFeedCompleted(this, new GetXmlFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/spaces/v1/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/", IsNullable=false)]
    public partial class AuthTokenHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(linkTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(headType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bodyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class linkType {
        
        private string linkColorField;
        
        private string backgroundColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string linkColor {
            get {
                return this.linkColorField;
            }
            set {
                this.linkColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string backgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(headType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bodyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class linkTextType : linkType {
        
        private string textColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string textColor {
            get {
                return this.textColorField;
            }
            set {
                this.textColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bodyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class headType : linkTextType {
        
        private string backgroundImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string backgroundImage {
            get {
                return this.backgroundImageField;
            }
            set {
                this.backgroundImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class bodyType : headType {
        
        private string secondaryLinkColorField;
        
        private string dividerColorField;
        
        private string accordionHoverColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string secondaryLinkColor {
            get {
                return this.secondaryLinkColorField;
            }
            set {
                this.secondaryLinkColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dividerColor {
            get {
                return this.dividerColorField;
            }
            set {
                this.dividerColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accordionHoverColor {
            get {
                return this.accordionHoverColorField;
            }
            set {
                this.accordionHoverColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class liveThemeType {
        
        private string themeNameField;
        
        private headType headField;
        
        private bodyType bodyField;
        
        private linkType actionsField;
        
        /// <remarks/>
        public string themeName {
            get {
                return this.themeNameField;
            }
            set {
                this.themeNameField = value;
            }
        }
        
        /// <remarks/>
        public headType head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        public bodyType body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public linkType actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class borderType {
        
        private string topLeftImageField;
        
        private string bottomLeftImageField;
        
        private string topRightImageField;
        
        private string bottomRightImageField;
        
        private string outlineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string topLeftImage {
            get {
                return this.topLeftImageField;
            }
            set {
                this.topLeftImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bottomLeftImage {
            get {
                return this.bottomLeftImageField;
            }
            set {
                this.bottomLeftImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string topRightImage {
            get {
                return this.topRightImageField;
            }
            set {
                this.topRightImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bottomRightImage {
            get {
                return this.bottomRightImageField;
            }
            set {
                this.bottomRightImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outline {
            get {
                return this.outlineField;
            }
            set {
                this.outlineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clientAreaType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class surfaceType {
        
        private string backgroundField;
        
        private string foregroundField;
        
        private string fontFaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string background {
            get {
                return this.backgroundField;
            }
            set {
                this.backgroundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string foreground {
            get {
                return this.foregroundField;
            }
            set {
                this.foregroundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fontFace {
            get {
                return this.fontFaceField;
            }
            set {
                this.fontFaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class clientAreaType : surfaceType {
        
        private string backgroundImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string backgroundImage {
            get {
                return this.backgroundImageField;
            }
            set {
                this.backgroundImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class themeType {
        
        private string nameField;
        
        private surfaceType titleBarField;
        
        private clientAreaType clientAreaField;
        
        private surfaceType toolbarField;
        
        private borderType borderField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public surfaceType titleBar {
            get {
                return this.titleBarField;
            }
            set {
                this.titleBarField = value;
            }
        }
        
        /// <remarks/>
        public clientAreaType clientArea {
            get {
                return this.clientAreaField;
            }
            set {
                this.clientAreaField = value;
            }
        }
        
        /// <remarks/>
        public surfaceType toolbar {
            get {
                return this.toolbarField;
            }
            set {
                this.toolbarField = value;
            }
        }
        
        /// <remarks/>
        public borderType border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(spaceContactCardElementsElementPhotoSubElement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class subelementBaseType {
        
        private string descriptionField;
        
        private string tooltipField;
        
        private string titleField;
        
        private string urlField;
        
        private System.DateTime lastUpdatedField;
        
        private bool lastUpdatedFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string tooltip {
            get {
                return this.tooltipField;
            }
            set {
                this.tooltipField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdatedSpecified {
            get {
                return this.lastUpdatedFieldSpecified;
            }
            set {
                this.lastUpdatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class spaceContactCardElementsElementPhotoSubElement : subelementBaseType {
        
        private string thumbnailUrlField;
        
        private string webReadyUrlField;
        
        private string albumNameField;
        
        /// <remarks/>
        public string thumbnailUrl {
            get {
                return this.thumbnailUrlField;
            }
            set {
                this.thumbnailUrlField = value;
            }
        }
        
        /// <remarks/>
        public string webReadyUrl {
            get {
                return this.webReadyUrlField;
            }
            set {
                this.webReadyUrlField = value;
            }
        }
        
        /// <remarks/>
        public string albumName {
            get {
                return this.albumNameField;
            }
            set {
                this.albumNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class elementType {
        
        private string titleField;
        
        private string urlField;
        
        private string totalNewItemsField;
        
        private subelementBaseType[] subElementField;
        
        private string typeField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string totalNewItems {
            get {
                return this.totalNewItemsField;
            }
            set {
                this.totalNewItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subElement")]
        public subelementBaseType[] subElement {
            get {
                return this.subElementField;
            }
            set {
                this.subElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class elementsType {
        
        private elementType[] elementField;
        
        private string totalMatchesField;
        
        private string returnedMatchesField;
        
        private string displayNameField;
        
        private string displayPictureUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("element")]
        public elementType[] element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalMatches {
            get {
                return this.totalMatchesField;
            }
            set {
                this.totalMatchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string returnedMatches {
            get {
                return this.returnedMatchesField;
            }
            set {
                this.returnedMatchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayPictureUrl {
            get {
                return this.displayPictureUrlField;
            }
            set {
                this.displayPictureUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class contactCardType {
        
        private string storageAuthCacheField;
        
        private elementsType elementsField;
        
        private themeType themeField;
        
        private liveThemeType liveThemeField;
        
        private System.DateTime lastUpdateField;
        
        /// <remarks/>
        public string storageAuthCache {
            get {
                return this.storageAuthCacheField;
            }
            set {
                this.storageAuthCacheField = value;
            }
        }
        
        /// <remarks/>
        public elementsType elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
        
        /// <remarks/>
        public themeType theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
            }
        }
        
        /// <remarks/>
        public liveThemeType liveTheme {
            get {
                return this.liveThemeField;
            }
            set {
                this.liveThemeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class GetXmlFeedResultType {
        
        private contactCardType contactCardField;
        
        /// <remarks/>
        public contactCardType contactCard {
            get {
                return this.contactCardField;
            }
            set {
                this.contactCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class GetXmlFeedResponseType {
        
        private GetXmlFeedResultType getXmlFeedResultField;
        
        /// <remarks/>
        public GetXmlFeedResultType GetXmlFeedResult {
            get {
                return this.getXmlFeedResultField;
            }
            set {
                this.getXmlFeedResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class refreshInformationType {
        
        private string cidField;
        
        private string storageAuthCacheField;
        
        private string marketField;
        
        private string brandField;
        
        private string maxElementCountField;
        
        private string maxCharacterCountField;
        
        private string maxImageCountField;
        
        private string applicationIdField;
        
        private bool updateAccessedTimeField;
        
        private System.DateTime spaceLastViewedField;
        
        private bool spaceLastViewedFieldSpecified;
        
        private bool isActiveContactField;
        
        private System.DateTime profileLastViewedField;
        
        private bool profileLastViewedFieldSpecified;
        
        private System.DateTime contactProfileLastViewedField;
        
        private bool contactProfileLastViewedFieldSpecified;
        
        private System.DateTime activeContactLastChangedField;
        
        private bool activeContactLastChangedFieldSpecified;
        
        public refreshInformationType() {
            this.maxElementCountField = "2";
            this.maxCharacterCountField = "200";
            this.maxImageCountField = "6";
            this.updateAccessedTimeField = true;
        }
        
        /// <remarks/>
        public string cid {
            get {
                return this.cidField;
            }
            set {
                this.cidField = value;
            }
        }
        
        /// <remarks/>
        public string storageAuthCache {
            get {
                return this.storageAuthCacheField;
            }
            set {
                this.storageAuthCacheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="language")]
        public string market {
            get {
                return this.marketField;
            }
            set {
                this.marketField = value;
            }
        }
        
        /// <remarks/>
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string maxElementCount {
            get {
                return this.maxElementCountField;
            }
            set {
                this.maxElementCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string maxCharacterCount {
            get {
                return this.maxCharacterCountField;
            }
            set {
                this.maxCharacterCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string maxImageCount {
            get {
                return this.maxImageCountField;
            }
            set {
                this.maxImageCountField = value;
            }
        }
        
        /// <remarks/>
        public string applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        public bool updateAccessedTime {
            get {
                return this.updateAccessedTimeField;
            }
            set {
                this.updateAccessedTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime spaceLastViewed {
            get {
                return this.spaceLastViewedField;
            }
            set {
                this.spaceLastViewedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool spaceLastViewedSpecified {
            get {
                return this.spaceLastViewedFieldSpecified;
            }
            set {
                this.spaceLastViewedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isActiveContact {
            get {
                return this.isActiveContactField;
            }
            set {
                this.isActiveContactField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime profileLastViewed {
            get {
                return this.profileLastViewedField;
            }
            set {
                this.profileLastViewedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool profileLastViewedSpecified {
            get {
                return this.profileLastViewedFieldSpecified;
            }
            set {
                this.profileLastViewedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime contactProfileLastViewed {
            get {
                return this.contactProfileLastViewedField;
            }
            set {
                this.contactProfileLastViewedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contactProfileLastViewedSpecified {
            get {
                return this.contactProfileLastViewedFieldSpecified;
            }
            set {
                this.contactProfileLastViewedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime activeContactLastChanged {
            get {
                return this.activeContactLastChangedField;
            }
            set {
                this.activeContactLastChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeContactLastChangedSpecified {
            get {
                return this.activeContactLastChangedFieldSpecified;
            }
            set {
                this.activeContactLastChangedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/spaces/v1/")]
    public partial class GetXmlFeedRequestType {
        
        private refreshInformationType refreshInformationField;
        
        /// <remarks/>
        public refreshInformationType refreshInformation {
            get {
                return this.refreshInformationField;
            }
            set {
                this.refreshInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetXmlFeedCompletedEventHandler(object sender, GetXmlFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXmlFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXmlFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetXmlFeedResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetXmlFeedResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591