using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyTitleAttribute("MSNPSharp")]
[assembly: AssemblyDescriptionAttribute(".NET MSN Messenger library")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2002-2006 Xih Solutions [b.geertsema@xihsolutions.net]")]
[assembly: AssemblyProductAttribute("MSNPSharp")]
[assembly: AssemblyDelaySignAttribute(false)]

[assembly: AssemblyFileVersionAttribute("2.0.0.0")]
