//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSNPSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSNPSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Messenger Client 9.0 的本地化字符串。
        /// </summary>
        internal static string ApplicationStrId {
            get {
                return ResourceManager.GetString("ApplicationStrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.1.2.1435 的本地化字符串。
        /// </summary>
        internal static string DeltasListVersion {
            get {
                return ResourceManager.GetString("DeltasListVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MSNPSharp_logo {
            get {
                object obj = ResourceManager.GetObject("MSNPSharp_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 MSN Explorer/9.0 (MSN 8.0; TmstmpExt) 的本地化字符串。
        /// </summary>
        internal static string WebServiceUserAgent {
            get {
                return ResourceManager.GetString("WebServiceUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3B119D87-1D76-4474-91AD-0D7267E86D04 的本地化字符串。
        /// </summary>
        internal static string WhatsupServiceAppID {
            get {
                return ResourceManager.GetString("WhatsupServiceAppID", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WLXLarge_default {
            get {
                object obj = ResourceManager.GetObject("WLXLarge_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 3.1.2.1435 的本地化字符串。
        /// </summary>
        internal static string XMLContactListVersion {
            get {
                return ResourceManager.GetString("XMLContactListVersion", resourceCulture);
            }
        }
    }
}
