//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSNPSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSNPSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger Client 9.0.
        /// </summary>
        internal static string ApplicationStrId {
            get {
                return ResourceManager.GetString("ApplicationStrId", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap default_image {
            get {
                object obj = ResourceManager.GetObject("default_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_scene {
            get {
                object obj = ResourceManager.GetObject("default_scene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0.0.2295.
        /// </summary>
        internal static string DeltasListVersion {
            get {
                return ResourceManager.GetString("DeltasListVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F679201A-DBC9-4011-B81B-3D05F0797EA9.
        /// </summary>
        internal static string DirectoryServiceAppID {
            get {
                return ResourceManager.GetString("DirectoryServiceAppID", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MSNPSharp_logo {
            get {
                object obj = ResourceManager.GetObject("MSNPSharp_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN Explorer/9.0 (MSN 8.0; TmstmpExt).
        /// </summary>
        internal static string WebServiceUserAgent {
            get {
                return ResourceManager.GetString("WebServiceUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3B119D87-1D76-4474-91AD-0D7267E86D04.
        /// </summary>
        internal static string WhatsupServiceAppID {
            get {
                return ResourceManager.GetString("WhatsupServiceAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0.0.2295.
        /// </summary>
        internal static string XMLContactListVersion {
            get {
                return ResourceManager.GetString("XMLContactListVersion", resourceCulture);
            }
        }
    }
}
